services:
  manager:
    build:
      context: ./manager
    ports:
      - "8000:8000"
    depends_on:
      - ocr
      - translate
  ocr:
    build:
      context: ./ocr
    environment:
      - AIP_HTTP_PORT=8001
      - MODEL_GCS_PATH=/models
    ports:
      - "8001:8001"
    volumes:
      - ./ocr/models:/models 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  translate:
    build:
      context: ./translate
    environment:
      - AIP_HTTP_PORT=8002
      - MODEL_GCS_PATH=/models/Hy-MT2-7B
    ports:
      - "8002:8002"
    volumes:
      - ./translate/Hy-MT2-7B:/models/Hy-MT2-7B 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]